[package]
name = "d1x"
version = "0.2.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
serde_json = "1.0.133"
termcolor = "1.4.1"
tokio = { version = "1.41.1", features = ["full"] }
tokio-tungstenite = "0.24.0"
